on:
  push:
    tags:
      - "v*.*.*"
    branch:
      - "main"
  workflow_dispatch:
permissions:
  contents: write
name: Expo Build
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup node
        uses: actions/setup-node@v3
      
      - name: 🏗 Install yarn
        run: npm i -g yarn
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Build app
        run: mkdir builds; eas build -p ios --local --non-interactive --output builds/build.ipa

      - name: 📦 Publish ipa to releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./builds/build.ipa
          asset_name: "app.ipa"
          tag: ${{ github.ref }}
          overwrite: true

      - name: 🏗 Install ios-uploader
        run: npm install -g ios-uploader

      - name: 📦 Upload ipa to TestFlight
        shell: bash
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          ios-uploader upload -u $APPLE_ID -p $APPLE_PASSWORD -f ./builds/build.ipa